In [1]:
import torch

In [ ]:
#!pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126

In [2]:
torch.__version__

'2.9.1+cu126'

In [3]:
torch.cuda.is_available()

True

In [6]:
import torch.nn.functional as F
from torch.autograd import grad

In [7]:
y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

In [10]:
z = x1*w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a,y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

# by default pytorch destroys the computational graph after calculating the gradient to free the memory. however, since we will reuse this graph, we set retain_graph=True so that it stays in memory.

In [9]:
print(grad_L_b)
print(grad_L_w1)

(tensor([-0.0817]),)
(tensor([-0.0898]),)


In [4]:
## below code implements a classic multilayer perceptron with two hidden layers.

In [12]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(

        #1st Hdden layer
        torch.nn.Linear(num_inputs,30),
        torch.nn.ReLU(),

        #2nd Hidden layer
        torch.nn.Linear(30,20),
        torch.nn.ReLU(),

        #Output layer
        torch.nn.Linear(20,num_outputs),

        )

    def forward(self,x):
        logits = self.layers(x)
        return logits

In [13]:
# Coding the number of inputs and output as variable allows us to reuse the same code for datasets with different number of features and classes.
# outputs of last layer are called logits

In [16]:
model = NeuralNetwork(50,3)

In [11]:
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [12]:
model = NeuralNetwork(20,5)

In [13]:
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=20, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=5, bias=True)
  )
)


In [16]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total number of trainable parameters:", num_params) 

Total number of trainable parameters: 1355


In [18]:
print(model.layers[0].weight)
# weight of first linear layer

Parameter containing:
tensor([[-2.0585e-01, -1.5003e-01,  7.9018e-02,  1.3178e-01, -8.6512e-02,
          1.6206e-02,  1.8117e-01, -1.7900e-01, -2.2038e-01,  1.8780e-01,
         -6.4889e-02, -6.0051e-02,  2.1622e-01, -8.8767e-02, -1.3706e-01,
         -1.7119e-01, -1.5554e-01, -8.2008e-03,  2.1049e-01, -2.2416e-02],
        [ 4.0243e-02,  7.8156e-02, -7.9628e-02,  1.5585e-01, -2.1511e-01,
          2.0166e-01, -1.7736e-01, -2.1352e-01,  9.6366e-02, -1.0868e-01,
          1.8298e-01, -1.7060e-01, -1.1362e-01, -1.7655e-01, -1.0376e-02,
          1.9466e-01, -7.4428e-02, -2.2074e-01,  1.8106e-01, -8.1676e-02],
        [-8.4951e-02,  8.8603e-02, -1.4757e-01, -1.7759e-01, -7.5682e-02,
          9.9159e-03,  8.9988e-02,  8.8557e-02,  4.2173e-02, -3.7912e-02,
         -8.2877e-02, -2.9220e-02,  1.2743e-01,  4.3593e-02,  2.1217e-01,
          1.8781e-01, -1.1534e-02, -3.7263e-02, -9.4915e-02, -1.3212e-01],
        [-8.7268e-02,  6.4154e-02,  8.4438e-02,  4.6602e-03,  1.5514e-01,
         -1.6

In [14]:
# requires_grad is set as true since its trainable, this is the default setting in torch.nn.Linear

In [20]:
print(model.layers[0].weight.shape)

torch.Size([30, 20])


In [21]:
print(model.layers[0].bias)

Parameter containing:
tensor([ 0.0139, -0.1702, -0.1029, -0.1091, -0.0155, -0.0200, -0.1900,  0.1057,
        -0.2192,  0.1666,  0.1635, -0.0639, -0.1036, -0.0073,  0.0589,  0.0638,
        -0.0532,  0.1107,  0.0836, -0.0815,  0.1542, -0.0032, -0.1654,  0.2190,
         0.0669,  0.1712,  0.0468,  0.0075, -0.0506,  0.2130],
       requires_grad=True)


In [17]:
model = NeuralNetwork(50,3)
# model is neural network which expect input vector of 50-dimension, passes it through all layers which we have already defined
torch.manual_seed(123)
X = torch.rand((1,50))
out = model(X)
print(X)
print(out)

tensor([[0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665, 0.1366, 0.1025, 0.1841,
         0.7264, 0.3153, 0.6871, 0.0756, 0.1966, 0.3164, 0.4017, 0.1186, 0.8274,
         0.3821, 0.6605, 0.8536, 0.5932, 0.6367, 0.9826, 0.2745, 0.6584, 0.2775,
         0.8573, 0.8993, 0.0390, 0.9268, 0.7388, 0.7179, 0.7058, 0.9156, 0.4340,
         0.0772, 0.3565, 0.1479, 0.5331, 0.4066, 0.2318, 0.4545, 0.9737, 0.4606,
         0.5159, 0.4220, 0.5786, 0.9455, 0.8057]])
tensor([[-0.0879,  0.1729,  0.1534]], grad_fn=<AddmmBackward0>)


In [18]:
# grad_fn represents last used function to calculate variable. Addmm stands fro matrix multipliation followed by addition

In [21]:
# if we want to use the network for prediction 
with torch.no_grad():
    out=model(X)

print(out)

tensor([[-0.0879,  0.1729,  0.1534]])


In [22]:
# in Pytorch its common practice to code models without passing output layer outputs to any non-linear function. becasue Pytorch commonly used loss function combine softmax or sigmoid (for bibary) 
# with negative loss-likelihood. if we want to calculate class membership probabilities for our predictions, we have to call the softmax fucntion explicitly.

with torch.no_grad():
    out = torch.softmax(model(X), dim=1)

print(out)

tensor([[0.2801, 0.3635, 0.3565]])


## Setting up efficient data loaders

In [24]:
X_train = torch.tensor([
    [-1.2,3.1],
    [-0.9,2.9],
    [-0.5,2.6],
    [2.3,-1.1],
    [2.7,-1.5]
])

y_train = torch.tensor([0,0,0,1,1])

X_test = torch.tensor([
    [-0.8,2.8],
    [2.6,-1.6]
])

y_test = torch.tensor([0,1])

# PyTorch requires class labels to start with 0 so if we have 3 classes it would be 0,1 and 2

In [25]:
# Now we will create a custom dataset class ToyDataset by subclassing from Pytorch's dataset parent class
from torch.utils.data import Dataset

class ToyDataset(Dataset):
    def __init__(self,X,y):
        self.features=X
        self.labels=y

    def __getitem__(self, index):   #1
        one_x=self.features[index]
        one_y=self.labels[index]
        return one_x,one_y

    def __len__(self):
        return self.labels.shape[0]  #2

train_ds = ToyDataset(X_train,y_train)
test_ds = ToyDataset(X_test,y_test)

#1 intructions to retrieve one data record and corresponding label
#2 instructions for returning the total length of the dataset.


In [27]:
print(len(train_ds))

5


In [29]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

train_loader = DataLoader(
    dataset=train_ds, #1
    batch_size=2,
    shuffle=True,  #2
    num_workers=0  #3
)

test_loader = DataLoader(
    dataset=test_ds,
    batch_size=2,
    shuffle=False, #4
    num_workers=0
)

#1 the Toydataset instance created earlier serves as input to dta loader
#2 whether or not to shuffle the data
#3 number of background processes
#4 not necessary to shuffle t test dataset

In [30]:
for idx, (x,y) in enumerate(train_loader):
    print(f" Batch {idx+1}:",x,y)

 Batch 1: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
 Batch 2: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
 Batch 3: tensor([[ 2.7000, -1.5000]]) tensor([1])


In [32]:
# train_loader is iterating over training dataset and visiting each example only once in a batch of 2 hence last batch contains only one example.
# you can remove that by adding drop_last function

train_loader = DataLoader(
    dataset=train_ds, #1
    batch_size=2,
    shuffle=True,  #2
    num_workers=0,  #3
    drop_last=True
)

for idx, (x,y) in enumerate(train_loader):
    print(f" Batch {idx+1}:",x,y)

 Batch 1: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
 Batch 2: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])


## A typical training loop

In [35]:
import torch.nn.functional as F

torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)  #1
optimizer = torch.optim.SGD(model.parameters(),lr=0.5)  #2

num_epochs = 3

for epoch in range(num_epochs):

    model.train()
    for batch_idx,(features,labels) in enumerate(train_loader):
        logits = model(features)

        loss = F.cross_entropy(logits,labels)

        optimizer.zero_grad()  #3
        loss.backward()  #4
        optimizer.step()  #5

        ###LOGGING
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx:03d}/{len(train_loader):03d}"
              f" |Train Loss: {loss:.2f}")

    model.eval()

#1 the dataset has two features and two classes
#2 The optimizer needs to know which paramaetrs to optimize
#3 set the gradients from previous round to 0 to avoid unintended gradient accumulation
#4 Computes the gradient of the loss given the model parametrs
#5 the optimizer uses the gradients to update the model parametrs



Epoch: 001/003 | Batch 000/002 |Train Loss: 0.75
Epoch: 001/003 | Batch 001/002 |Train Loss: 0.65
Epoch: 002/003 | Batch 000/002 |Train Loss: 0.44
Epoch: 002/003 | Batch 001/002 |Train Loss: 0.13
Epoch: 003/003 | Batch 000/002 |Train Loss: 0.03
Epoch: 003/003 | Batch 001/002 |Train Loss: 0.00


In [36]:
# Now that we have trained the model, lets use it for prediction
model.eval()
with torch.no_grad():
    outputs=model(X_train)

print(outputs)

tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])


In [37]:
# to obtain class membership probabilities
torch.set_printoptions(sci_mode=False)
proba = torch.softmax(outputs,dim=1)
print(proba)

tensor([[0.9991, 0.0009],
        [0.9982, 0.0018],
        [0.9949, 0.0051],
        [0.0491, 0.9509],
        [0.0307, 0.9693]])


In [38]:
# we can convert these values into class label using argmax, which returns the index position of highest value in each row if we set dim=1, dim=0 will return highest value for column
predictions = torch.argmax(proba,dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [39]:
predictions = torch.argmax(outputs,dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [40]:
def compute_accuracy(model,dataloader):
    model = model.eval()
    correct = 0.0
    total_examples = 0

    for idx,(features,labels) in enumerate(dataloader):

        with torch.no_grad():
            logits = model(features)

        predictions = torch.argmax(logits,dim=1)
        compare = labels==predictions
        correct+=torch.sum(compare)
        total_examples+=len(compare)

    return (correct/total_examples).item()

In [42]:
print(compute_accuracy(model,train_loader))

1.0


In [43]:
print(compute_accuracy(model,test_loader))

1.0


## Optimizing Training performance with GPU

In [44]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4,5,6])
print(tensor_1+tensor_2)

tensor([5, 7, 9])


In [45]:
# by default these tensor are loaded on cpu and computation will also be carried out on cpu

In [46]:
tensor_1 = tensor_1.to("cuda")
tensor_2 = tensor_2.to("cuda")
print(tensor_1+tensor_2)

tensor([5, 7, 9], device='cuda:0')


In [48]:
#if you have multiple multiple GPU's you can mention cuda:0 or cuda:1 but both tensor should be on same device to perform computations

In [49]:
import torch.nn.functional as F

torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)  

device = torch.device("cuda") #1
model = model.to("cuda") #2

optimizer = torch.optim.SGD(model.parameters(),lr=0.5)  

num_epochs = 3

for epoch in range(num_epochs):

    model.train()
    for batch_idx,(features,labels) in enumerate(train_loader):
        features,labels = features.to(device), labels.to(device)  #3
        logits = model(features)

        loss = F.cross_entropy(logits,labels)

        optimizer.zero_grad()  #3
        loss.backward()  #4
        optimizer.step()  #5

        ###LOGGING
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx:03d}/{len(train_loader):03d}"
              f" |Train Loss: {loss:.2f}")

    model.eval()

#1 define the variable device that defaults to GPU
#2 transfer the model ontp the GPU
#3 transfer the data to GPU

Epoch: 001/003 | Batch 000/002 |Train Loss: 0.75
Epoch: 001/003 | Batch 001/002 |Train Loss: 0.65
Epoch: 002/003 | Batch 000/002 |Train Loss: 0.44
Epoch: 002/003 | Batch 001/002 |Train Loss: 0.13
Epoch: 003/003 | Batch 000/002 |Train Loss: 0.03
Epoch: 003/003 | Batch 001/002 |Train Loss: 0.00


In [ ]:
# can also use
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")